name: where_to_go_today
description: Куда пойти сегодня?

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  bloc: ^8.0.0
  dio: ^4.0.0
  equatable: ^2.0.0
  firebase_auth: ^3.3.6
  firebase_auth_web: ^3.3.7
  firebase_core: ^1.12.0
  firebase_core_web: ^1.5.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_login_vk: ^2.2.0
  flutter_mobx: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.3
  google_sign_in_web: ^0.10.0+4
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  mask_text_input_formatter: ^2.1.0
  mobx: ^2.0.0
  provider: ^6.0.0
  retrofit: ^3.0.1
  routemaster: ^0.9.0
  rxdart: ^0.27.0

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.1.2
  dart_code_metrics: ^4.9.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  golden_toolkit: ^0.13.0
  mobx_codegen: ^2.0.0
  mocktail: ^0.2.0
  retrofit_generator: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/3.0x/
    - assets/images/auth/sign_in/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat-v21-latin_cyrillic-regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat-v21-latin_cyrillic-500.ttf
          weight: 500
        - asset: assets/fonts/montserrat-v21-latin_cyrillic-600.ttf
          weight: 600
        - asset: assets/fonts/montserrat-v21-latin_cyrillic-700.ttf
          weight: 700
